puts "The students of Villains Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the west"
puts "Terminator"
puts "Freddie Kreuger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
